apiVersion: networking.cloud.tencent.com/v1alpha1
kind: CLBPortPool
metadata:
  name: port-pool-ctcc
spec:
  startPort: 30000 # 端口池的起始端口号
  endPort: 65000 # 端口池的结束端口号
  segmentLength: 100 # 端口段的长度，如指定该字段，这端口池中所有端口均使用端口段类型的监听器
  region: ap-chengdu # 端口池中 CLB 所在地域
  exsistedLoadBalancerIDs: [lb-xxx, lb-yyy] # 向端口池中添加已有 CLB，可选
  autoCreate:
    enabled: true # 是否自动创建 CLB (端口不够的情况下)
    parameters: # 自动创建 CLB 的参数
      vipIsp: CTCC # 仅适用于公网负载均衡。目前仅广州、上海、南京、济南、杭州、福州、北京、石家庄、武汉、长沙、成都、重庆地域支持静态单线 IP 线路类型，如需体验，请联系商务经理申请。申请通过后，即可选择中国移动（CMCC）、中国联通（CUCC）或中国电信（CTCC）的运营商类型，网络计费模式只能使用按带宽包计费(BANDWIDTH_PACKAGE)。 如果不指定本参数，则默认使用BGP。可通过 DescribeResources 接口查询一个地域所支持的Isp。
      bandwidthPackageId: bwp-xxxxxxxx # 带宽包ID，指定此参数时，网络计费方式（InternetAccessible.InternetChargeType）只支持按带宽包计费（BANDWIDTH_PACKAGE），带宽包的属性即为其结算方式。非上移用户购买的 IPv6 负载均衡实例，且运营商类型非 BGP 时 ，不支持指定具体带宽包id。
      addressIPVersion: "IPv6FullChain" # 仅适用于公网负载均衡。IP版本，可取值：IPV4、IPV6、IPv6FullChain，不区分大小写，默认值 IPV4。说明：取值为IPV6表示为IPV6 NAT64版本；取值为IPv6FullChain，表示为IPv6版本。
      loadBalancerPassToTarget: "" # Target是否放通来自CLB的流量。开启放通（true）：只验证CLB上的安全组；不开启放通（false）：需同时验证CLB和后端实例上的安全组。默认值为 true。
      dynamicVip: "" # 是否创建域名化负载均衡。
      # 负载均衡后端目标设备所属的网络 ID，如vpc-12345678，可以通过 DescribeVpcs 接口获取。 不填此参数则默认为当前集群所在 VPC。创建内网负载均衡实例时，此参数必填。
      vpcId: ""
      # 仅适用于公网负载均衡。目前仅广州、上海、南京、济南、杭州、福州、北京、石家庄、武汉、长沙、成都、重庆地域支持静态单线 IP 线路类型，如需体验，请联系商务经理申请。申请通过后，即可选择中国移动（CMCC）、中国联通（CUCC）或中国电信（CTCC）的运营商类型，网络计费模式只能使用按带宽包计费(BANDWIDTH_PACKAGE)。 如果不指定本参数，则默认使用BGP。可通过 DescribeResources 接口查询一个地域所支持的Isp。
      vip: ""
      tags: # 购买负载均衡的同时，给负载均衡打上标签，最大支持20个标签键值对。
      - tagKey: "test-key" # 标签的键
        tagValue: "test-value" # 标签的值
      projectId: 0 # 负载均衡实例所属的项目 ID，可以通过 DescribeProject 接口获取。不填此参数则视为默认项目。
      loadBalancerName: "test-lb" # 负载均衡实例的名称，只在创建一个实例的时候才会生效。规则：1-60 个英文、汉字、数字、连接线“-”或下划线“_”。 注意：如果名称与系统中已有负载均衡实例的名称相同，则系统将会自动生成此次创建的负载均衡实例的名称。
      loadBalancerType: "" # 负载均衡实例的网络类型：OPEN：公网属性， INTERNAL：内网属性。
      # 仅适用于公网且IP版本为IPv4的负载均衡。设置跨可用区容灾时的主可用区ID，例如 100001 或 ap-guangzhou-1
      # 注：主可用区是需要承载流量的可用区，备可用区默认不承载流量，主可用区不可用时才使用备可用区。目前仅广州、上海、南京、北京、成都、深圳金融、中国香港、首尔、法兰克福、新加坡地域的 IPv4 版本的 CLB 支持主备可用区。可通过 DescribeResources 接口查询一个地域的主可用区的列表。【如果您需要体验该功能，请通过 工单申请】
      masterZoneId: "ap-guangzhou-1"
      zoneId: "ap-guangzhou-1" # 仅适用于公网且IP版本为IPv4的负载均衡。可用区ID，指定可用区以创建负载均衡实例。
      subnetId: subnet-xxxxxxxx # 在私有网络内购买内网负载均衡实例的情况下，必须指定子网 ID，内网负载均衡实例的 VIP 将从这个子网中产生。创建内网负载均衡实例时，此参数必填，创建公网IPv4负载均衡实例时，不支持指定该参数。
      # 性能容量型规格。
      # 若需要创建性能容量型实例，则此参数必填，取值范围：
      # clb.c2.medium：标准型规格
      # clb.c3.small：高阶型1规格
      # clb.c3.medium：高阶型2规格
      # clb.c4.small：超强型1规格
      # clb.c4.medium：超强型2规格
      # clb.c4.large：超强型3规格
      # clb.c4.xlarge：超强型4规格
      # 若需要创建共享型实例，则无需填写此参数。
      slaType: "clb.c4.xlarge"
      lbChargeType: POSTPAID_BY_HOUR # 负载均衡实例计费类型，取值：POSTPAID_BY_HOUR，PREPAID，默认是POSTPAID_BY_HOUR。
      internetAccessible:
        internetChargeType: "BANDWIDTH_POSTPAID_BY_HOUR" # TRAFFIC_POSTPAID_BY_HOUR 按流量按小时后计费 ; BANDWIDTH_POSTPAID_BY_HOUR 按带宽按小时后计费; BANDWIDTH_PACKAGE 按带宽包计费;BANDWIDTH_PREPAID按带宽预付费。注意：此字段可能返回 null，表示取不到有效值。
        # 最大出带宽，单位Mbps，仅对公网属性的共享型、性能容量型和独占型 CLB 实例、以及内网属性的性能容量型 CLB 实例生效。
        # - 对于公网属性的共享型和独占型 CLB 实例，最大出带宽的范围为1Mbps-2048Mbps。
        # - 对于公网属性和内网属性的性能容量型 CLB实例，最大出带宽的范围为1Mbps-61440Mbps。
        # （调用CreateLoadBalancer创建LB时不指定此参数则设置为默认值10Mbps。此上限可调整）
        internetMaxBandwidthOut: "100"
        bandwidthpkgSubType: "SINGLEISP" # 带宽包的类型，如SINGLEISP（单线）、BGP（多线）。
      extensiveParameters: "" # 其它 CreateLoadBalancer 扩展参数，json 格式。详细参数列表请参考 https://cloud.tencent.com/document/api/214/30692
status:
  state: Active
  message: ""
  loadbalancerStatuses:
  - loadbalancerID: lb-xxx
    loadbalancerName: test1
    ips: [1.1.1.1]
    hostname: lb-xxx.tencent.com
  - loadbalancerID: lb-yyy
    loadbalancerName: test2
    state: Normal
    ips: [1.1.1.1]
    hostname: lb-xxx.tencent.com
