---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networking-cloud-tencent-com-v1alpha1-dedicatedclblistener
  failurePolicy: Fail
  name: mdedicatedclblistener.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dedicatedclblisteners
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networking-cloud-tencent-com-v1alpha1-clbportpool
  failurePolicy: Fail
  name: mclbportpool-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clbportpools
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-cloud-tencent-com-v1alpha1-dedicatedclblistener
  failurePolicy: Fail
  name: vdedicatedclblistener.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dedicatedclblisteners
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate--v1-pod
  failurePolicy: Fail
  name: vpod-v1.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-cloud-tencent-com-v1alpha1-clbpodbinding
  failurePolicy: Fail
  name: vclbpodbinding-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clbpodbindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-cloud-tencent-com-v1alpha1-clbportpool
  failurePolicy: Fail
  name: vclbportpool-v1alpha1.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clbportpools
  sideEffects: None
