---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networking-cloud-tencent-com-v1alpha1-dedicatedclblistener
  failurePolicy: Fail
  name: mdedicatedclblistener.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dedicatedclblisteners
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-cloud-tencent-com-v1alpha1-dedicatedclblistener
  failurePolicy: Fail
  name: vdedicatedclblistener.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dedicatedclblisteners
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-cloud-tencent-com-v1beta1-dedicatedclblistener
  failurePolicy: Fail
  name: vdedicatedclblistener-v1beta1.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dedicatedclblisteners
  sideEffects: None
