apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tke-extend-network-controller
    app.kubernetes.io/managed-by: kustomize
  name: webhook-service
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: tke-extend-network-controller
