# This rule is not used by the project tke-extend-network-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over networking.cloud.tencent.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tke-extend-network-controller
    app.kubernetes.io/managed-by: kustomize
  name: clbnodebinding-admin-role
rules:
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbnodebindings
  verbs:
  - '*'
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbnodebindings/status
  verbs:
  - get
