# permissions for end users to edit dedicatedmulticlbservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tke-extend-network-controller
    app.kubernetes.io/managed-by: kustomize
  name: dedicatedmulticlbservice-editor-role
rules:
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedmulticlbservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedmulticlbservices/status
  verbs:
  - get
