---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tke-extend-network-controller-role
rules:
- apiGroups:
  - agones.dev
  resources:
  - gameservers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - game.kruise.io
  resources:
  - gameserversets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.kruise.io
  resources:
  - gameserversets/status
  verbs:
  - get
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbnodebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbnodebindings/finalizers
  verbs:
  - update
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbnodebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbpodbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbpodbindings/finalizers
  verbs:
  - update
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbpodbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbportpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbportpools/finalizers
  verbs:
  - update
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - clbportpools/status
  verbs:
  - get
  - patch
  - update
