apiVersion: networking.cloud.tencent.com/v1beta1
kind: DedicatedCLBListener
metadata:
  labels:
    app.kubernetes.io/name: tke-extend-network-controller
    app.kubernetes.io/managed-by: kustomize
  name: dedicatedclblistener-sample
spec:
  # TODO(user): Add fields here
