//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLB) DeepCopyInto(out *CLB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLB.
func (in *CLB) DeepCopy() *CLB {
	if in == nil {
		return nil
	}
	out := new(CLB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CLB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBHealthcheck) DeepCopyInto(out *CLBHealthcheck) {
	*out = *in
	if in.HealthSwitch != nil {
		in, out := &in.HealthSwitch, &out.HealthSwitch
		*out = new(int64)
		**out = **in
	}
	if in.TimeOut != nil {
		in, out := &in.TimeOut, &out.TimeOut
		*out = new(int64)
		**out = **in
	}
	if in.IntervalTime != nil {
		in, out := &in.IntervalTime, &out.IntervalTime
		*out = new(int64)
		**out = **in
	}
	if in.HealthNum != nil {
		in, out := &in.HealthNum, &out.HealthNum
		*out = new(int64)
		**out = **in
	}
	if in.UnHealthNum != nil {
		in, out := &in.UnHealthNum, &out.UnHealthNum
		*out = new(int64)
		**out = **in
	}
	if in.HttpCode != nil {
		in, out := &in.HttpCode, &out.HttpCode
		*out = new(int64)
		**out = **in
	}
	if in.HttpCheckPath != nil {
		in, out := &in.HttpCheckPath, &out.HttpCheckPath
		*out = new(string)
		**out = **in
	}
	if in.HttpCheckDomain != nil {
		in, out := &in.HttpCheckDomain, &out.HttpCheckDomain
		*out = new(string)
		**out = **in
	}
	if in.HttpCheckMethod != nil {
		in, out := &in.HttpCheckMethod, &out.HttpCheckMethod
		*out = new(string)
		**out = **in
	}
	if in.CheckPort != nil {
		in, out := &in.CheckPort, &out.CheckPort
		*out = new(int64)
		**out = **in
	}
	if in.ContextType != nil {
		in, out := &in.ContextType, &out.ContextType
		*out = new(string)
		**out = **in
	}
	if in.SendContext != nil {
		in, out := &in.SendContext, &out.SendContext
		*out = new(string)
		**out = **in
	}
	if in.RecvContext != nil {
		in, out := &in.RecvContext, &out.RecvContext
		*out = new(string)
		**out = **in
	}
	if in.CheckType != nil {
		in, out := &in.CheckType, &out.CheckType
		*out = new(string)
		**out = **in
	}
	if in.HttpVersion != nil {
		in, out := &in.HttpVersion, &out.HttpVersion
		*out = new(string)
		**out = **in
	}
	if in.SourceIpType != nil {
		in, out := &in.SourceIpType, &out.SourceIpType
		*out = new(int64)
		**out = **in
	}
	if in.ExtendedCode != nil {
		in, out := &in.ExtendedCode, &out.ExtendedCode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBHealthcheck.
func (in *CLBHealthcheck) DeepCopy() *CLBHealthcheck {
	if in == nil {
		return nil
	}
	out := new(CLBHealthcheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBList) DeepCopyInto(out *CLBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CLB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBList.
func (in *CLBList) DeepCopy() *CLBList {
	if in == nil {
		return nil
	}
	out := new(CLBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CLBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBListenerConfig) DeepCopyInto(out *CLBListenerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBListenerConfig.
func (in *CLBListenerConfig) DeepCopy() *CLBListenerConfig {
	if in == nil {
		return nil
	}
	out := new(CLBListenerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CLBListenerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBListenerConfigList) DeepCopyInto(out *CLBListenerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CLBListenerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBListenerConfigList.
func (in *CLBListenerConfigList) DeepCopy() *CLBListenerConfigList {
	if in == nil {
		return nil
	}
	out := new(CLBListenerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CLBListenerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBListenerConfigSpec) DeepCopyInto(out *CLBListenerConfigSpec) {
	*out = *in
	if in.Healthcheck != nil {
		in, out := &in.Healthcheck, &out.Healthcheck
		*out = new(CLBHealthcheck)
		(*in).DeepCopyInto(*out)
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(Certificate)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionExpireTime != nil {
		in, out := &in.SessionExpireTime, &out.SessionExpireTime
		*out = new(int64)
		**out = **in
	}
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(string)
		**out = **in
	}
	if in.SniSwitch != nil {
		in, out := &in.SniSwitch, &out.SniSwitch
		*out = new(int64)
		**out = **in
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(string)
		**out = **in
	}
	if in.SessionType != nil {
		in, out := &in.SessionType, &out.SessionType
		*out = new(string)
		**out = **in
	}
	if in.KeepaliveEnable != nil {
		in, out := &in.KeepaliveEnable, &out.KeepaliveEnable
		*out = new(int64)
		**out = **in
	}
	if in.EndPort != nil {
		in, out := &in.EndPort, &out.EndPort
		*out = new(uint64)
		**out = **in
	}
	if in.DeregisterTargetRst != nil {
		in, out := &in.DeregisterTargetRst, &out.DeregisterTargetRst
		*out = new(bool)
		**out = **in
	}
	if in.MultiCertInfo != nil {
		in, out := &in.MultiCertInfo, &out.MultiCertInfo
		*out = new(MultiCertInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxConn != nil {
		in, out := &in.MaxConn, &out.MaxConn
		*out = new(int64)
		**out = **in
	}
	if in.MaxCps != nil {
		in, out := &in.MaxCps, &out.MaxCps
		*out = new(int64)
		**out = **in
	}
	if in.IdleConnectTimeout != nil {
		in, out := &in.IdleConnectTimeout, &out.IdleConnectTimeout
		*out = new(int64)
		**out = **in
	}
	if in.SnatEnable != nil {
		in, out := &in.SnatEnable, &out.SnatEnable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBListenerConfigSpec.
func (in *CLBListenerConfigSpec) DeepCopy() *CLBListenerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CLBListenerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBListenerConfigStatus) DeepCopyInto(out *CLBListenerConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBListenerConfigStatus.
func (in *CLBListenerConfigStatus) DeepCopy() *CLBListenerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CLBListenerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBSpec) DeepCopyInto(out *CLBSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBSpec.
func (in *CLBSpec) DeepCopy() *CLBSpec {
	if in == nil {
		return nil
	}
	out := new(CLBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLBStatus) DeepCopyInto(out *CLBStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLBStatus.
func (in *CLBStatus) DeepCopy() *CLBStatus {
	if in == nil {
		return nil
	}
	out := new(CLBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertInfo) DeepCopyInto(out *CertInfo) {
	*out = *in
	if in.CertId != nil {
		in, out := &in.CertId, &out.CertId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertInfo.
func (in *CertInfo) DeepCopy() *CertInfo {
	if in == nil {
		return nil
	}
	out := new(CertInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certificate) DeepCopyInto(out *Certificate) {
	*out = *in
	if in.SSLMode != nil {
		in, out := &in.SSLMode, &out.SSLMode
		*out = new(string)
		**out = **in
	}
	if in.CertId != nil {
		in, out := &in.CertId, &out.CertId
		*out = new(string)
		**out = **in
	}
	if in.CertCaId != nil {
		in, out := &in.CertCaId, &out.CertCaId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certificate.
func (in *Certificate) DeepCopy() *Certificate {
	if in == nil {
		return nil
	}
	out := new(Certificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedCLBListener) DeepCopyInto(out *DedicatedCLBListener) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedCLBListener.
func (in *DedicatedCLBListener) DeepCopy() *DedicatedCLBListener {
	if in == nil {
		return nil
	}
	out := new(DedicatedCLBListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedCLBListener) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedCLBListenerList) DeepCopyInto(out *DedicatedCLBListenerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DedicatedCLBListener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedCLBListenerList.
func (in *DedicatedCLBListenerList) DeepCopy() *DedicatedCLBListenerList {
	if in == nil {
		return nil
	}
	out := new(DedicatedCLBListenerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedCLBListenerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedCLBListenerSpec) DeepCopyInto(out *DedicatedCLBListenerSpec) {
	*out = *in
	if in.DedicatedTarget != nil {
		in, out := &in.DedicatedTarget, &out.DedicatedTarget
		*out = new(DedicatedTarget)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedCLBListenerSpec.
func (in *DedicatedCLBListenerSpec) DeepCopy() *DedicatedCLBListenerSpec {
	if in == nil {
		return nil
	}
	out := new(DedicatedCLBListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedCLBListenerStatus) DeepCopyInto(out *DedicatedCLBListenerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedCLBListenerStatus.
func (in *DedicatedCLBListenerStatus) DeepCopy() *DedicatedCLBListenerStatus {
	if in == nil {
		return nil
	}
	out := new(DedicatedCLBListenerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedCLBService) DeepCopyInto(out *DedicatedCLBService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedCLBService.
func (in *DedicatedCLBService) DeepCopy() *DedicatedCLBService {
	if in == nil {
		return nil
	}
	out := new(DedicatedCLBService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedCLBService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedCLBServiceList) DeepCopyInto(out *DedicatedCLBServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DedicatedCLBService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedCLBServiceList.
func (in *DedicatedCLBServiceList) DeepCopy() *DedicatedCLBServiceList {
	if in == nil {
		return nil
	}
	out := new(DedicatedCLBServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedCLBServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedCLBServiceSpec) DeepCopyInto(out *DedicatedCLBServiceSpec) {
	*out = *in
	if in.ExistedLbIds != nil {
		in, out := &in.ExistedLbIds, &out.ExistedLbIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedCLBServiceSpec.
func (in *DedicatedCLBServiceSpec) DeepCopy() *DedicatedCLBServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DedicatedCLBServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedCLBServiceStatus) DeepCopyInto(out *DedicatedCLBServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedCLBServiceStatus.
func (in *DedicatedCLBServiceStatus) DeepCopy() *DedicatedCLBServiceStatus {
	if in == nil {
		return nil
	}
	out := new(DedicatedCLBServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedNatgwService) DeepCopyInto(out *DedicatedNatgwService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedNatgwService.
func (in *DedicatedNatgwService) DeepCopy() *DedicatedNatgwService {
	if in == nil {
		return nil
	}
	out := new(DedicatedNatgwService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedNatgwService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedNatgwServiceList) DeepCopyInto(out *DedicatedNatgwServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DedicatedNatgwService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedNatgwServiceList.
func (in *DedicatedNatgwServiceList) DeepCopy() *DedicatedNatgwServiceList {
	if in == nil {
		return nil
	}
	out := new(DedicatedNatgwServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DedicatedNatgwServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedNatgwServiceSpec) DeepCopyInto(out *DedicatedNatgwServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedNatgwServiceSpec.
func (in *DedicatedNatgwServiceSpec) DeepCopy() *DedicatedNatgwServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DedicatedNatgwServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedNatgwServiceStatus) DeepCopyInto(out *DedicatedNatgwServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedNatgwServiceStatus.
func (in *DedicatedNatgwServiceStatus) DeepCopy() *DedicatedNatgwServiceStatus {
	if in == nil {
		return nil
	}
	out := new(DedicatedNatgwServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DedicatedTarget) DeepCopyInto(out *DedicatedTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DedicatedTarget.
func (in *DedicatedTarget) DeepCopy() *DedicatedTarget {
	if in == nil {
		return nil
	}
	out := new(DedicatedTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiCertInfo) DeepCopyInto(out *MultiCertInfo) {
	*out = *in
	if in.SSLMode != nil {
		in, out := &in.SSLMode, &out.SSLMode
		*out = new(string)
		**out = **in
	}
	if in.CertList != nil {
		in, out := &in.CertList, &out.CertList
		*out = make([]CertInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiCertInfo.
func (in *MultiCertInfo) DeepCopy() *MultiCertInfo {
	if in == nil {
		return nil
	}
	out := new(MultiCertInfo)
	in.DeepCopyInto(out)
	return out
}
