# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/networking.cloud.tencent.com_dedicatedclbservices.yaml
- bases/networking.cloud.tencent.com_dedicatedclblisteners.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# - path: patches/webhook_in_clbpodbindings.yaml
- path: patches/webhook_in_dedicatedclblisteners.yaml
- path: patches/webhook_in_dedicatedclbservices.yaml
  # +kubebuilder:scaffold:crdkustomizewebhookpatch

configurations:
- kustomizeconfig.yaml
